### ISSUE TITLE
Incorrect/Incomplete Search Results

### ISSUE THREAD

**Issue by Nzzyme** [SvDvorak/BandcampMultitagSearch#10]
I entered the following keywords:

soundscapes
atmospheric
ambient

and I see few albums in the search results. But I believe this is not the complete list. For example, I know an album that has the above three keywords for sure but it did not show up in the results on campexplorer

Ex: https://maxcorbacho.bandcamp.com/album/breathstream

Can you please check and fix this?

**Comment by SvDvorak** [comment]
Yeah, this is a known issue because of the fact that the data source I'm getting albums from has a limit on number albums returned for each tag/keyword. So it's impossible for me to get a complete list sadly, there isn't anything I can do until Bandcamp makes their API public.
