### ISSUE TITLE
Add playback directly from CampExplorer page

### ISSUE THREAD

**Issue by SvDvorak** [SvDvorak/BandcampMultitagSearch#21]
Currently you have to click on the album to go to the album page and then play it to even hear what the album sounds like. Similar to [Bandcamp Explorer](https://bc-explorer.app/) it would be nice to be able to play a song from a search result listing.

**Comment by cvzi** [comment]
BTW this is already possible with my bandcamp user-script: https://github.com/cvzi/Bandcamp-script-deluxe-edition

**Comment by SvDvorak** [comment]
Interesting, I did not know that. I'll try to ensure that this change will not collide with your script then.
