### ISSUE TITLE
Add a link to the live version

### ISSUE THREAD

**Issue by cvzi** [SvDvorak/BandcampMultitagSearch#23]
When someone finds this repository, they have to use Google to find the web address and it doesn't appear on the first page of Google results (at least for me).

It would be convenient to have a link to https://campexplorer.io/ either in the readme or in the github repo description.

And possibly a link to install the extension as well, although that is the first google result for me.

**Comment by SvDvorak** [comment]
Sorry for the slow response, thought I had already responded. Great idea! I never thought that people would find this repository first but instead that they would come here from the website itself. Adding it to the readme and description now.
